# This network will be used by all Docker containers that need to respond to reverse proxy requests.
- name: Create a reverse proxy network
  docker_network:
    name: reverse-proxy

# Filesystem location for Docker container definitions.
- name: Create directory for Docker containers
  file:
    path: /srv/containers
    state: directory
    owner: deploy
    group: deploy
    mode: "2775"

- name: Install Traefik reverse proxy
  git:
    repo: https://github.com/jfredrickson/tensouth-proxy.git
    dest: /srv/containers/tensouth-proxy

- name: Start Traefik reverse proxy
  docker_service:
    project_src: /srv/containers/tensouth-proxy/traefik
