# This network will be used by all Docker containers that need to respond to reverse proxy requests.
- name: Create a reverse proxy network
  docker_network:
    name: reverse-proxy

# Filesystem location for Docker container definitions.
- name: Creates directory
  file:
    path: /srv/containers
    state: directory
    owner: deploy
    group: deploy
    mode: 2775
