- name: Create a reverse proxy network
  docker_network:
    name: reverse-proxy

- name: Create directory for Docker containers
  file:
    path: /srv/containers
    state: directory
    owner: deploy
    group: deploy
    mode: "2775"

- name: Install Traefik reverse proxy
  git:
    repo: https://github.com/jfredrickson/tensouth-proxy.git
    dest: /srv/containers/tensouth-proxy

- name: Ensure Traefik certificate store has proper permissions
  file:
    path: /srv/containers/tensouth-proxy/traefik/acme.json
    mode: 0600

- name: Start Traefik reverse proxy
  docker_service:
    project_src: /srv/containers/tensouth-proxy/traefik
