- hosts: all
  become: yes
  become_user: root
  roles:
    - users
    - ssh
    - geerlingguy.firewall
    - geerlingguy.pip
    - geerlingguy.docker
    - docker
    - backups
    - system
  vars_files:
    - vars.yml
    - aws.yml
